# Generated by Django 5.2.9 on 2025-12-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('disco_solicitado', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='disco',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
