# Generated by Django 5.2.9 on 2025-12-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pedido_alter_disco_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='artista',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='nombre_cliente',
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(default='Desconocido', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='disco_solicitado',
            field=models.CharField(max_length=200),
        ),
    ]
