# Generated by Django 6.0.1 on 2026-01-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_rename_artista_pedido_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
